### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by nooberjones** [marlon360/vr-graph#62]
Hello, 

I appreciate your work, it's great.  I am trying to build this app and I get two errors, below.

Uncaught TypeError: Cannot read properties of undefined (reading 'function')
    at ar.html:201:85

ar.6d9dbea….bundle.js:2 Uncaught (in promise) TypeError: THREE.PlaneBufferGeometry is not a constructor
    at i.createSurface (ar.6d9dbea23d0743734…bundle.js:2:2373074)
    at i.createGraph (ar.6d9dbea23d0743734…bundle.js:2:2368937)
    at i.init (ar.6d9dbea23d0743734…bundle.js:2:2367575)
    at i.initComponent (ar.6d9dbea23d0743734…bundle.js:2:1146603)
    at i.updateProperties (ar.6d9dbea23d0743734…bundle.js:2:1146316)
    at u.updateComponent (ar.6d9dbea23d0743734…bundle.js:2:1134966)
    at u.updateComponents (ar.6d9dbea23d0743734…bundle.js:2:1134845)
    at ar.6d9dbea23d0743734…bundle.js:2:1132944
    at ar.6d9dbea23d0743734…bundle.js:2:1141574

any help would be appreciated. 

Thanks,

**Comment by brisdaz** [comment]
Have you received any help?

**Comment by EricEisaman** [comment]
@nooberjones 
This project is currently pinned to "three": "^0.111.0", as you can see in the package json.  That version of ThreeJS is really old.  If you update the project to the current ThreeJS and manage the conflicts you will solve your issue and also have something to contribute back in a PR.

**Comment by nooberjones** [comment]
OK, I got it to build! YAY!  If I deploy like that it uses your backend, as I noticed? I am trying to build the backend now.
